---
language: generic
# Use the new container infrastructure
sudo: required

env:
  - PHP_VERSION=7.1 SYMFONY_VERSION=3
  - PHP_VERSION=7.1 SYMFONY_VERSION=4
  - PHP_VERSION=7.2 SYMFONY_VERSION=3
  - PHP_VERSION=7.2 SYMFONY_VERSION=4

services:
  - docker

cache:
  directories:
    - $HOME/.composer

install:
  - cd $PHP_VERSION
  # Build image
  - sudo docker build . -t kibatic/symfony:$PHP_VERSION
  # Check installed php version
  - sudo docker run -it kibatic/symfony:$PHP_VERSION php --version | grep "PHP $PHP_VERSION"
  - sudo docker build -f tests/Dockerfile . -t kibatic/symfony-demo:$PHP_VERSION
  - export SYMFONY_DEMO_VERSION=$([ "$SYMFONY_VERSION" = "4" ] && echo "v1.3.1" || echo "v1.0.5")

script:
  - git clone --branch $SYMFONY_DEMO_VERSION https://github.com/symfony/symfony-demo symfony; cd symfony
  - sudo docker run --rm -v $(pwd):/var/www -v $HOME/.composer:/root/.composer kibatic/symfony-demo:$PHP_VERSION composer install --no-progress || true
  - sudo docker run -d -p 8001:80 -e SYMFONY_VERSION=$SYMFONY_VERSION -v $(pwd):/var/www kibatic/symfony-demo:$PHP_VERSION
  - sleep 10
  - sudo docker run --rm $( (( "$SYMFONY_DEMO_VERSION" = "v1.0.5" )) && printf %s "-e SYMFONY_PHPUNIT_VERSION=5.7.27" ) -e SYMFONY_DEPRECATIONS_HELPER=disabled -v $(pwd):/var/www kibatic/symfony-demo:$PHP_VERSION vendor/bin/simple-phpunit
  - curl -s localhost:8001 | grep -q "Welcome to the <strong>Symfony Demo</strong> application"

notifications:
  email: true
